/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.adventofcode.day1

import kotlin.test.*

class ProgramTest {

    private val program by lazy { Program() }

    @Test
    fun `should return false when given numbers sum does not equal 2020`() {
        assertFalse(program.isSolution(-1, 0))
        assertFalse(program.isSolution(1000, 1019))
    }

    @Test
    fun `should return true when given numbers sum equals 2020`() {
        assertTrue(program.isSolution(1000, 1020))
        assertTrue(program.isSolution(1000, 1020))
        assertTrue(program.isSolution(2019, 1))
        assertTrue(program.isSolution(2020, 0))
        assertTrue(program.isSolution(0, 2020))
    }

    @Test
    fun `should return null when given input is not a solution`() {
        // Given
        val list = listOf(1, 5456, -22, 1000, 45)

        // When
        val result = program.getSolution(1000, list)

        // Then
        assertNull(result)
    }

    @Test
    fun `should return solution when given input is a solution`() {
        // Given
        val list = listOf(1, 5456, -22, 2019, 45)

        // When
        val result = program.getSolution(1, list)

        // Then
        assertEquals(Solution(1, 2019, 2019), result)
    }
}
