/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.adventofcode

import kotlin.reflect.full.createInstance
import kotlin.time.ExperimentalTime
import kotlin.time.measureTimedValue

@ExperimentalTime
fun main(args: Array<String>) {
    val dayNumber = args.first().toInt()

    println("ADVENT OF CODE 2020 : DAY #$dayNumber".toTitle())

    val dayProgram = Class.forName("com.adventofcode.day$dayNumber.Program")
            .kotlin.createInstance()

    if (dayProgram is IsDayProgram<*>) {
        val timedValue = measureTimedValue {
            dayProgram.run(dayNumber)
        }
        val durationInMs = timedValue.duration.toLongMilliseconds()
        val solution = timedValue.value
        println("\nDay #$dayNumber program complete in $durationInMs ms \n→ $solution")
    } else {
        error("No program found for day #$dayNumber")
    }
}

private fun String.toTitle(): String {
    val separator = "=".repeat(length)
    return """
        $separator
        $this
        $separator
    """.trimIndent()
}