/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.adventofcode.day1

import com.adventofcode.IsDayProgram
import java.io.File

class Program : IsDayProgram<Solution> {

    override fun run(dayNumber: Int): Solution {

        val numbers = File(javaClass.getResource("/day1/inputs").toURI())
                .readLines()
                .map(String::toInt)

        numbers.forEach { input ->
            getSolution(input, numbers)?.let { solution -> return solution }
        }

        error("No solution found!")
    }

    fun getSolution(input: Int, numbers: List<Int>): Solution? {
        numbers.forEach { number ->
            if (isSolution(input, number)) {
                return Solution(input, number)
            }
        }
        return null
    }

    fun isSolution(n1: Int, n2: Int): Boolean = n1 + n2 == 2020

}