/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.adventofcode.day1

import com.adventofcode.IsDayProgram
import java.io.File

class Program : IsDayProgram<Pair<Solution, Solution>> {

    override fun run(dayNumber: Int): Pair<Solution, Solution> {

        val numbers = File(javaClass.getResource("/day1/inputs").toURI())
                .readLines()
                .map(String::toInt)

        // Find solution with two entries
        val twoEntriesSolution: Solution? = numbers.findSolution(2)

        // Find solution with three entries
        val threeEntriesSolution: Solution? = numbers.findSolution(3)

        if (twoEntriesSolution == null || threeEntriesSolution == null) {
            error("Missing solution(s)!")
        } else {
            return twoEntriesSolution to threeEntriesSolution
        }
    }

    fun List<Int>.findSolution(index: Int, vararg inputs: Int): Solution? {
        if (index == 0) {
            if (isSolution(*inputs)) {
                return Solution(*inputs)
            }
        } else {
            forEach { number ->
                findSolution(index - 1, *(inputs + number))?.let {
                    return it
                }
            }
        }
        return null
    }

    fun isSolution(vararg numbers: Int): Boolean = numbers.sum() == 2020

}